name: CTests

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
  schedule:
        - cron: '16 5 * * *'


jobs:
  full-chain-test:
    strategy:
      matrix:
        source_opt: ["", "-n"]
        image: ["alma9"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - name: Start container
      run: |
        docker run -it \
                   --name CI_container \
                   -v ${GITHUB_WORKSPACE}:/Package \
                   -v /cvmfs:/cvmfs:shared \
                   -d ghcr.io/key4hep/key4hep-images/alma9:latest /bin/bash
    - name: Run tests
      run: |
        docker exec CI_container /bin/bash -c \
        source setup.sh ${{ matrix.source_opt }};\
        cmake -B build -S . &&  ctest --test-dir build/
